/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation.repartidor;

import co.unicauca.openmarket.client.domain.service.BuyService;
import co.unicauca.openmarket.commons.domain.Buy;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SANTIAGO
 */
public class jpRecogerProducto extends javax.swing.JPanel {

    /**
     * Creates new form jpRecogerProducto
     */
    private BuyService buyService;

    public jpRecogerProducto(BuyService buyService) {
        this.buyService = buyService;
        initComponents();
        initializeTableVentas();
        cargarDatos();
        //cargarDatos();
    }

    private void addCheckbox(int column, JTable table) {
        TableColumn tb = table.getColumnModel().getColumn(column);
        tb.setCellEditor(table.getDefaultEditor(Boolean.class));
        tb.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }

    private boolean isSelected(int row, int column, JTable table) {
        return table.getValueAt(row, column) != null;
    }

    private void initializeTableVentas() {

        tblRecogerProducto.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id Producto", "Id Comprador", "Id Venta", "Estado", "fecha", "Seleccionar"
                }
        ));

        addCheckbox(5, tblRecogerProducto);
    }

    private List<Buy> getLsyBuyEnviadas() throws Exception {
        List<Buy> buys = buyService.findAllBuys();
        List<Buy> buysEnviadas = new ArrayList<>();

        for (Buy buy : buys) {
            if (buy.getEstado().equalsIgnoreCase("Realizada")) {
                buysEnviadas.add(buy);
            }
        }

        return buysEnviadas;
    }

    public void cargarDatos() {
        try {
            fillTableVentas(getLsyBuyEnviadas());
        } catch (Exception ex) {
            Logger.getLogger(jpRecogerProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillTableVentas(List<Buy> listVentas) {
        initializeTableVentas();
        DefaultTableModel model = (DefaultTableModel) tblRecogerProducto.getModel();

        Object rowData[] = new Object[5];//No columnas
        for (int i = 0; i < listVentas.size(); i++) {
            rowData[0] = listVentas.get(i).getProductoId();
            rowData[1] = listVentas.get(i).getCompradorId();
            rowData[2] = listVentas.get(i).getId();
            rowData[3] = listVentas.get(i).getEstado();
            rowData[4] = listVentas.get(i).getFechaCompra();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecogerProducto = new javax.swing.JTable();
        lblMessage2 = new javax.swing.JLabel();
        lblMessage1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEntregar1 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 64, 91));

        tblRecogerProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecogerProducto);

        lblMessage2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblMessage2.setForeground(new java.awt.Color(242, 204, 143));
        lblMessage2.setText("esta entrega será confirmada por el comprador ");

        lblMessage1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblMessage1.setForeground(new java.awt.Color(242, 204, 143));
        lblMessage1.setText("En esta sección deberas seleccionar las compras que deseas entregar a cada uno de los compradores , ");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione las compras que desea entregar:");

        btnEntregar1.setBackground(new java.awt.Color(224, 122, 95));
        btnEntregar1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEntregar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregar1.setText("Entregar");
        btnEntregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregar1ActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 204, 143));
        lblTitulo.setText("ENTREGAR COMPRAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMessage1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnEntregar1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEntregar1)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregar1ActionPerformed
        List<Buy> lstComprasSel = new ArrayList<>();
        List<Buy> lstCompras = null;
        try {
            lstCompras = getLsyBuyEnviadas();
        } catch (Exception ex) {
            Logger.getLogger(jpRecogerProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < tblRecogerProducto.getRowCount(); i++) {
            if (isSelected(i, 5, tblRecogerProducto)) {
                Buy buy = lstCompras.get(i);
                buy.setEstado("Entregado");
                lstComprasSel.add(buy);
            }
        }
        
        for(int i = 0; i <lstComprasSel.size(); i++){
            Buy buy = lstComprasSel.get(i);
            try {
                buyService.editBuy(buy.getId(), buy);
            } catch (Exception ex) {
                Logger.getLogger(jpRecogerProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        cargarDatos();
    }//GEN-LAST:event_btnEntregar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage1;
    private javax.swing.JLabel lblMessage2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblRecogerProducto;
    // End of variables declaration//GEN-END:variables
}
