package co.unicauca.openmarket.client.presentation.vendedor;

/**
 *
 * @author juan
 */
public class JpAgregarCategoria extends javax.swing.JPanel {
    
    /**
     * Creates new form jpAgregarCategoria
     */
    public JpAgregarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdCategoria = new javax.swing.JLabel();
        lbNombreCategoria = new javax.swing.JLabel();
        txtIdCategoria = new javax.swing.JTextField();
        txtNombreCategoria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgregarCategoria = new javax.swing.JTable();

        setBackground(new java.awt.Color(61, 64, 91));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIdCategoria.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbIdCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbIdCategoria.setText("ID");
        add(lbIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lbNombreCategoria.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbNombreCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreCategoria.setText("Nombre");
        add(lbNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, -1));
        add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(224, 122, 95));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, -1));

        btnDeshacer.setBackground(new java.awt.Color(224, 122, 95));
        btnDeshacer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 90, -1));

        tblAgregarCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAgregarCategoria);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 240));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdCategoria;
    private javax.swing.JLabel lbNombreCategoria;
    private javax.swing.JTable tblAgregarCategoria;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
