package co.unicauca.openmarket.client.presentation.vendedor;

/**
 *
 * @author juan
 */
public class JpAgregarProducto extends javax.swing.JPanel {
    
    /**
     * Creates new form JpAgregarProducto
     */
    public JpAgregarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdProducto = new javax.swing.JLabel();
        lbNombreProducto = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbIdCategoria = new javax.swing.JLabel();
        lbLocacion = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();
        txtLocacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAgregarProducto = new javax.swing.JTable();

        setBackground(new java.awt.Color(61, 64, 91));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIdProducto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbIdProducto.setText("ID");
        add(lbIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lbNombreProducto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreProducto.setText("Nombre");
        add(lbNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        lbPrecio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecio.setText("Precio");
        add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lbIdCategoria.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbIdCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbIdCategoria.setText("Categoria");
        add(lbIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lbLocacion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbLocacion.setForeground(new java.awt.Color(255, 255, 255));
        lbLocacion.setText("Locación");
        add(lbLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        lbDescripcion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lbDescripcion.setText("Descripción");
        add(lbDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));
        add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 37, 223, -1));
        add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 83, 223, -1));
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 131, 223, -1));
        add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 178, 223, -1));
        add(txtLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 228, 223, -1));

        txtADescripcion.setColumns(20);
        txtADescripcion.setRows(5);
        jScrollPane1.setViewportView(txtADescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 270, -1, 74));

        btnGuardar.setBackground(new java.awt.Color(224, 122, 95));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 131, 100, -1));

        btnDeshacer.setBackground(new java.awt.Color(224, 122, 95));
        btnDeshacer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 210, 100, -1));

        tblAgregarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAgregarProducto);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 362, 547, 225));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbIdCategoria;
    private javax.swing.JLabel lbIdProducto;
    private javax.swing.JLabel lbLocacion;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JTable tblAgregarProducto;
    private javax.swing.JTextArea txtADescripcion;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtLocacion;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
