package co.unicauca.openmarket.client.presentation.vendedor;

/**
 *
 * @author juank
 */
public class JpBorrar extends javax.swing.JPanel {

    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpP;
    
    /**
     * Creates new form JpBorrar
     */
    public JpBorrar(javax.swing.JPanel jpContent, javax.swing.JPanel jpP) {
        this.jpContent = jpContent;
        this.jpP = jpP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdProducto = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        bntVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBorrar = new javax.swing.JTable();

        setBackground(new java.awt.Color(61, 64, 91));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIdProducto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbIdProducto.setText("ID");
        add(lbIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 122, -1, -1));
        add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 119, 300, -1));

        btnEliminar.setBackground(new java.awt.Color(224, 122, 95));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 185, 100, -1));

        btnDeshacer.setBackground(new java.awt.Color(224, 122, 95));
        btnDeshacer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 185, 100, -1));

        bntVolver.setBackground(new java.awt.Color(224, 122, 95));
        bntVolver.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bntVolver.setForeground(new java.awt.Color(255, 255, 255));
        bntVolver.setText("Volver");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });
        add(bntVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 185, 100, -1));

        tblBorrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBorrar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 279, 499, 272));
    }// </editor-fold>//GEN-END:initComponents

    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        jpP.setSize(700, 600);
        jpP.setLocation(0, 0);
        
        jpContent.removeAll();
        jpContent.add(jpP, new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_bntVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVolver;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdProducto;
    private javax.swing.JTable tblBorrar;
    private javax.swing.JTextField txtIdProducto;
    // End of variables declaration//GEN-END:variables
}
