package co.unicauca.openmarket.client.presentation.vendedor;

/**
 *
 * @author juan
 */
public class JpEditar extends javax.swing.JPanel {
    
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpP;
    
    /**
     * Creates new form JpEditar
     */
    public JpEditar(javax.swing.JPanel jpContent, javax.swing.JPanel jpP) {
        this.jpContent = jpContent;
        this.jpP = jpP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombreProducto = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbIdCategoria = new javax.swing.JLabel();
        lbLocacion = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        btnDeshacer = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();
        txtLocacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEditar = new javax.swing.JTable();

        setBackground(new java.awt.Color(61, 64, 91));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombreProducto.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreProducto.setText("Nombre");
        add(lbNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lbPrecio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecio.setText("Precio");
        add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lbIdCategoria.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbIdCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbIdCategoria.setText("Categoria");
        add(lbIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lbLocacion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbLocacion.setForeground(new java.awt.Color(255, 255, 255));
        lbLocacion.setText("Locación");
        add(lbLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lbDescripcion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lbDescripcion.setText("Descripción");
        add(lbDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        btnDeshacer.setBackground(new java.awt.Color(224, 122, 95));
        btnDeshacer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 100, -1));

        btnGuardar.setBackground(new java.awt.Color(224, 122, 95));
        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, -1));

        btnVolver.setBackground(new java.awt.Color(224, 122, 95));
        btnVolver.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 100, -1));
        add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, -1));
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, -1));
        add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));
        add(txtLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, -1));

        txtADescripcion.setColumns(20);
        txtADescripcion.setRows(5);
        jScrollPane1.setViewportView(txtADescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 80));

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEditar);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 535, 245));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        jpP.setSize(700, 600);
        jpP.setLocation(0, 0);
        
        jpContent.removeAll();
        jpContent.add(jpP, new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpContent.revalidate();
        jpContent.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbIdCategoria;
    private javax.swing.JLabel lbLocacion;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JTable tblEditar;
    private javax.swing.JTextArea txtADescripcion;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtLocacion;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
