package co.unicauca.openmarket.client.presentation.comprador;

import co.unicauca.openmarket.client.domain.service.BankAccountService;
import co.unicauca.openmarket.client.domain.service.BuyService;
import co.unicauca.openmarket.client.domain.service.CategoryService;
import co.unicauca.openmarket.client.domain.service.ProductService;
import co.unicauca.openmarket.commons.domain.User;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author nimbachi
 */
public class GUIComprador extends javax.swing.JFrame {

    private ProductService productService;
    private CategoryService categoryService;
    private BuyService buyService;
    private BankAccountService bankService;
    private User user;

    /**
     * Creates new form GUIComprador
     */
    public GUIComprador(ProductService productService, CategoryService categoryService, BuyService buyService, User user, BankAccountService bankService) {
        initComponents();
        this.productService = productService;
        this.categoryService = categoryService;
        this.buyService = buyService;
        this.bankService = bankService;
        this.user = user;
        this.deshabilitarFunciones();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * Deshabilita ciertas funciones dependiendo del estado del usuario. Si el
     * usuario es nulo, oculta los botones "Confirmar Entrega" y "Tus Entregas".
     */
    private void deshabilitarFunciones() {
        if (user == null) {
            this.btnConfirmarE.setVisible(false);
            this.btnTusEntregas.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentralC = new javax.swing.JPanel();
        jpOpcionesC = new javax.swing.JPanel();
        btnBuscarP = new javax.swing.JButton();
        btnConfirmarE = new javax.swing.JButton();
        btnTusEntregas = new javax.swing.JButton();
        lblNombreComprador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCentralC.setBackground(new java.awt.Color(61, 64, 91));
        jpCentralC.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpCentralC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 600));

        jpOpcionesC.setBackground(new java.awt.Color(224, 122, 95));
        jpOpcionesC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarP.setBackground(new java.awt.Color(242, 204, 143));
        btnBuscarP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBuscarP.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarP.setText("Buscar Producto");
        btnBuscarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 40));

        btnConfirmarE.setBackground(new java.awt.Color(242, 204, 143));
        btnConfirmarE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConfirmarE.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarE.setText("Confirmar Entregas");
        btnConfirmarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnConfirmarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));

        btnTusEntregas.setBackground(new java.awt.Color(242, 204, 143));
        btnTusEntregas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnTusEntregas.setForeground(new java.awt.Color(255, 255, 255));
        btnTusEntregas.setText("Tus Compras");
        btnTusEntregas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTusEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTusEntregasActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnTusEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        lblNombreComprador.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNombreComprador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreComprador.setText("Comprador");
        jpOpcionesC.add(lblNombreComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        getContentPane().add(jpOpcionesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        JPanel jpBuscar = new JPBuscarProductos(productService, categoryService, buyService, user, bankService);
        jpBuscar.setSize(700, 600);
        jpBuscar.setLocation(0, 0);

        jpCentralC.removeAll();
        jpCentralC.add(jpBuscar, BorderLayout.CENTER);
        jpCentralC.revalidate();
        jpCentralC.repaint();
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnConfirmarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEActionPerformed
        JPanel jpConfirmarE;
        try {
            jpConfirmarE = new JPConfirmarE(productService, categoryService, buyService, user);
            jpConfirmarE.setSize(700, 600);
            jpConfirmarE.setLocation(0, 0);

            jpCentralC.removeAll();
            jpCentralC.add(jpConfirmarE, BorderLayout.CENTER);
            jpCentralC.revalidate();
            jpCentralC.repaint();
        } catch (Exception ex) {
            Logger.getLogger(GUIComprador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarEActionPerformed

    private void btnTusEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTusEntregasActionPerformed
        JPanel jpTusCompras;
        try {
            jpTusCompras = new JPTusCompras(buyService, productService, user);
            jpTusCompras.setSize(700, 600);
            jpTusCompras.setLocation(0, 0);

            jpCentralC.removeAll();
            jpCentralC.add(jpTusCompras, BorderLayout.CENTER);
            jpCentralC.revalidate();
            jpCentralC.repaint();
        } catch (Exception ex) {
            Logger.getLogger(GUIComprador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTusEntregasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnConfirmarE;
    private javax.swing.JButton btnTusEntregas;
    private javax.swing.JPanel jpCentralC;
    private javax.swing.JPanel jpOpcionesC;
    private javax.swing.JLabel lblNombreComprador;
    // End of variables declaration//GEN-END:variables
}
