/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.openmarket.client.presentation.comprador;

import co.unicauca.openmarket.client.presentation.comprador.JPBuscarProductos;
import co.unicauca.openmarket.client.presentation.comprador.JPConfirmarE;
import co.unicauca.openmarket.client.presentation.comprador.JPTusCompras;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Hewlett Packard
 */
public class GUIComprador extends javax.swing.JFrame {

    /**
     * Creates new form GUIComprador
     */
    public GUIComprador() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentralC = new javax.swing.JPanel();
        jpOpcionesC = new javax.swing.JPanel();
        btnBuscarP = new javax.swing.JButton();
        btnConfirmarE = new javax.swing.JButton();
        btnTusEntregas = new javax.swing.JButton();
        lblNombreComprador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCentralC.setBackground(new java.awt.Color(61, 64, 91));
        jpCentralC.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpCentralC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 600));

        jpOpcionesC.setBackground(new java.awt.Color(224, 122, 95));
        jpOpcionesC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarP.setBackground(new java.awt.Color(242, 204, 143));
        btnBuscarP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnBuscarP.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarP.setText("Buscar Producto");
        btnBuscarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 40));

        btnConfirmarE.setBackground(new java.awt.Color(242, 204, 143));
        btnConfirmarE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnConfirmarE.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarE.setText("Confirmar Entregas");
        btnConfirmarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnConfirmarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));

        btnTusEntregas.setBackground(new java.awt.Color(242, 204, 143));
        btnTusEntregas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnTusEntregas.setForeground(new java.awt.Color(255, 255, 255));
        btnTusEntregas.setText("Tus Compras");
        btnTusEntregas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTusEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTusEntregasActionPerformed(evt);
            }
        });
        jpOpcionesC.add(btnTusEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        lblNombreComprador.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNombreComprador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreComprador.setText("Nombre del Comprador");
        jpOpcionesC.add(lblNombreComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        getContentPane().add(jpOpcionesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        JPanel jpBuscar = new JPBuscarProductos();
        jpBuscar.setSize(700, 600);
        jpBuscar.setLocation(0, 0);
        
        jpCentralC.removeAll();
        jpCentralC.add(jpBuscar, BorderLayout.CENTER);
        jpCentralC.revalidate();
        jpCentralC.repaint();
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnConfirmarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEActionPerformed
        JPanel jpConfirmarE = new JPConfirmarE();
        jpConfirmarE.setSize(700, 600);
        jpConfirmarE.setLocation(0, 0);
        
        jpCentralC.removeAll();
        jpCentralC.add(jpConfirmarE, BorderLayout.CENTER);
        jpCentralC.revalidate();
        jpCentralC.repaint();
    }//GEN-LAST:event_btnConfirmarEActionPerformed

    private void btnTusEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTusEntregasActionPerformed
        JPanel jpTusCompras = new JPTusCompras();
        jpTusCompras.setSize(700, 600);
        jpTusCompras.setLocation(0, 0);
        
        jpCentralC.removeAll();
        jpCentralC.add(jpTusCompras, BorderLayout.CENTER);
        jpCentralC.revalidate();
        jpCentralC.repaint();
    }//GEN-LAST:event_btnTusEntregasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnConfirmarE;
    private javax.swing.JButton btnTusEntregas;
    private javax.swing.JPanel jpCentralC;
    private javax.swing.JPanel jpOpcionesC;
    private javax.swing.JLabel lblNombreComprador;
    // End of variables declaration//GEN-END:variables
}
