/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation.comprador;

/**
 *
 * @author Hewlett Packard
 */
public class JPBuscarProductos extends javax.swing.JPanel {

    /**
     * Creates new form JPBuscarProductos
     */
    public JPBuscarProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPCentralBuscarP = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBuscarPor = new javax.swing.JLabel();
        cbxTipoBusqueda = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtValorIngresado = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductosO = new javax.swing.JTable();
        btnComprarPS = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPCentralBuscarP.setBackground(new java.awt.Color(61, 64, 91));
        JPCentralBuscarP.setForeground(new java.awt.Color(61, 64, 91));
        JPCentralBuscarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(242, 204, 143));
        lblTitulo.setText("BUSCAR PRODUCTOS");
        JPCentralBuscarP.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lblBuscarPor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblBuscarPor.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarPor.setText("Buscar por:");
        JPCentralBuscarP.add(lblBuscarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        cbxTipoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cbxTipoBusqueda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbxTipoBusqueda.setForeground(new java.awt.Color(224, 122, 95));
        cbxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Nombre", "Identificador", "Categoria" }));
        cbxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoBusquedaActionPerformed(evt);
            }
        });
        JPCentralBuscarP.add(cbxTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 320, -1));

        txtValorIngresado.setBackground(new java.awt.Color(255, 255, 255));
        txtValorIngresado.setBorder(null);
        txtValorIngresado.setForeground(new java.awt.Color(224, 122, 95));
        txtValorIngresado.setText("Ingrese el valor de la opcion seleccionada");
        jScrollPane1.setViewportView(txtValorIngresado);

        JPCentralBuscarP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 320, 20));

        tblProductosO.setBackground(new java.awt.Color(255, 255, 255));
        tblProductosO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Precio", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosO.setGridColor(new java.awt.Color(255, 255, 255));
        tblProductosO.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tblProductosO.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProductosO.setShowGrid(false);
        jScrollPane2.setViewportView(tblProductosO);

        JPCentralBuscarP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 560, 200));

        btnComprarPS.setBackground(new java.awt.Color(242, 204, 143));
        btnComprarPS.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnComprarPS.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarPS.setText("Comprar producto seleccionado");
        btnComprarPS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComprarPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPSActionPerformed(evt);
            }
        });
        JPCentralBuscarP.add(btnComprarPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 210, 30));

        lblInformacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(255, 255, 255));
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacion.setText("[Label de informacion al oprimir boton \"Compar\"]");
        JPCentralBuscarP.add(lblInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 320, -1));

        add(JPCentralBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoBusquedaActionPerformed

    private void btnComprarPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarPSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCentralBuscarP;
    private javax.swing.JButton btnComprarPS;
    private javax.swing.JComboBox<String> cbxTipoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProductosO;
    private javax.swing.JTextPane txtValorIngresado;
    // End of variables declaration//GEN-END:variables
}
